name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  JOB_COUNT: 3

jobs:
  build:
    name: Build SHOT
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install dependencies
      shell: bash
      run: sudo apt-get update ; sudo apt-get install -y libc6-dev libbz2-dev zlib1g-dev liblapack-dev libnauty2-dev libopenblas-base libopenblas-dev libmumps-dev

    - name: Cache Cbc
      id: cache-cbc
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/ThirdParty/Cbc
        key: ${{ runner.os }}-cbc

    - name: Cache Ipopt
      id: cache-ipopt
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/ThirdParty/Ipopt
        key: ${{ runner.os }}-ipopt

    - name: Setup Coinbrew
      if: steps.cache-ipopt.outputs.cache-hit != 'true' || steps.cache-cbc.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: git -C "coinbrew" pull || git clone https://github.com/coin-or/coinbrew

    - name: Download and build Ipopt
      if: steps.cache-ipopt.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{runner.workspace}}/build/coinbrew
      run: ./coinbrew build Ipopt --verbosity 2 --prefix=${{runner.workspace}}/ThirdParty/Ipopt -j $JOB_COUNT --no-prompt --tests none

    - name: Download and build Cbc
      if: steps.cache-cbc.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{runner.workspace}}/build/coinbrew
      run: rm -rf build dist ; ./coinbrew build Cbc@stable/2.10 --verbosity 2 -j $JOB_COUNT --prefix=${{runner.workspace}}/ThirdParty/Cbc --no-prompt --tests none --no-third-party

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHAS_CBC=on -DCBC_DIR=${{runner.workspace}}/ThirdParty/Cbc -DHAS_IPOPT=ON -DIPOPT_DIR=${{runner.workspace}}/ThirdParty/Ipopt -DHAS_GAMS=off -DHAS_CPLEX=off -DHAS_GUROBI=off -DCOMPILE_TESTS=on -DSPDLOG_STATIC=on

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -j $JOB_COUNT

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE --output-on-failure

    # Upload all the build files as artifacts.
    - uses: actions/upload-artifact@v3
      with:
        name: shot-build
        path: ${{runner.workspace}}/build
        retention-days: 4

